language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: hQ36nohJXuPtHq7pxWy3AIC3GS+fAmRaz9gizK/SFV70v72tGimGkHQq0QjQnLr01LPE+zbuHxpBJj1JGmhA953h8cDVG5SyIDEKpslGnlKx1qYeMd2RYZRc+jpjGlXCeyr/Aqo95uNpBCV5PmNWrkBCwibjAGH1Z++59q1geN2auYZNUvPJkCudy8iZ8G71HPFtZPO9FYTD/BJ7xz/SW3f2a4AcKLL2x4wyHAWDSsK0wtALrrGjKQcFV5T+NrpSLOriHn7KjvkmzuwYufAhQLn711WZ1deZ6ZsKHZI3CbzHkVzY0lP/a+CVV/e88qLM6V98orAWqZCrbDT98Wa23i9uJGHayh9NwhwpJ1YyVD1os43sr8Zm49JqxAMlKfb/VC8x5URV6RbF5nGWPks7/BFoqNgrRyYBN8P9dwjZ2bA/b4+GEFyW73e/koJdeJ2FmsMPnN1ur2BLbkJA7dubNhNCXQE/WSHIkh4lklCiFHzrYg2wng17yMybzL9oN8Q1gSF8n4PYsCSVpGmzbRPv/ZwlaATU+hNsQVQZfdPgUUgwc5/RDUEsR7e2jZNxZ0rt+WTDYwhYDLXTjn29yxmi7F9WfJHqpxAuRR7z+HnvXy5/CzB5QQLyfFU5Fyz70AiDXB+niANY+WrWGVOHLkEKhfogNUtS53VDr42okiUqd4w=
  app: kakumemo
