language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: IKLz4qQD9QRntJhOCGVI0TYJewXva043cGCyrVR5GBJ7KwvzJheWE2ScjksgPoKNtyax2qYfHJOKxrcsus7K7Ag1qCS/2KjkufiT12YjYaK2N1Wgg2ACBkbUbYB5XnPBRC3QzUCIagb/L8JrGgLIAbHwKrEL5dRwkEXtobvjPuLtnG0oP0jhOIFvy7GXXBOSDLi1cOFl6OI7rXlOx13p6lZ2Td7HEag4l3hefpKerHVwQh8I3BEc3CPGutI7vykxBeh2ngyTrf/bdCO615xHcLo/gBrcRFQLc+rfTpvl91fU0q7XaOpLeD7Nk+baoBb4THlHD1TIK9pI+p6fh9jSFKAxezbf8+UZPe2j4kiS4+RAbiTxePF9+7mqgIVGTGa113PTYYWwwpE/jqOZ27BP+dYtuB+6dzgaLndA4QeSOnrpWK+V9uoomTLkAUPgnB7hBC/zQcHR2OB4uFTlruDxhKNUwqHD9fcr7jQ3ycTYnNAdcr110qIsdT7vzvI1idZ+a/v2hTWzM9dk5KLVr91QkOqGVRV7R03DBad2O/VWo1NlGof390emM0XRgmST6SZ/CWERwuOs4deYm+gIIsU+QWbzPJIuR9beBx1QTowMJ+sVTdcgFgu1b7UiX4oPtYBy9hjXQYWi6x5bkw8YvP3xx66optBqxMExinzPjSBQEK4=
  app: kakumemo
  on:
    repo: full-party/CrossUp
