language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: rWTjlwD8PnOkXYpimimX8+kLunubFJIBfzpsocOl/R2TcWBeYpxi+VSj8AlpiyMi9QQX8wb0cqn9m9Q80yi9fu+FNTxWdNsqmlNLdzCg37qUEiSuY+JwL1cpLs9WU5nnxYbEWtmvIFFi5x5h/p3/q0zFQGkD95unYiv4QtVkLpMC1f3lTfx+6CJa3iUX9gJtBAWrCFxf07KevEzr/FXeBlnnlfPxrIVm+CmpZ5HjwfGZ9YtZqwz7hG+i47Wuwn3Eyf+p1xhzGSjjwud9n9ADydhAu3UVvyPZoOwV7v0fBdtttsqO9Y8E2TjtK6bAnXezPxkXk7eieNPxnD9iNzGwZaRtPBDyRJHyrDhPyfd26qlKEjMS7TKihXqidocRzgQXc1jiUh7KUFGEzML+FbdLqHSR1ZbCWoeM5OqDUhKgzqzvUmQd+FBqB4U6naoBV2UOVvLJ67k1sOvtomZLOlhWaAcD5V6Jr92sLODAb+q6lF9oEcq5FRAUUQQyRkiNVQKEFzzqRFHpDzj20Jp4IML0SQRYihRCZ3io8hDpBiMYBBbVMk4wPI6iBrq0dntc0vfB2bGm2fhZ7K2m+moYpCyZOcbynwtszSK89jmwijxgcVyfZ/Js3mQ3/twOca9dgr+ZdPQlCYWnFFe2or4FHp/JU7dhlhVjdq+NuKTasMj5wfE=
  app: kakumemo
  on:
    repo: full-party/CrossUp
  run:
  - php artisan migrate --force
