language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: RJCn+EmBhIYQSRZDCb72lgXYfQJREx1/i6fO3EuqpjW9bCbHA3buLdLKCcx/1lggUin/+z5Qh4Un4/UFB0at/zSg9yXSoCM8B3t5U30FMUTF1Dc7bbwi8RbtsT2XqNxrbLYz0sDg3FPKRkirxbT43x2b1O+zon34g85LSYC4UVOk2Q/GPnLGnX2bqLUHMwiJ1m6Oj9bKw7kH4+W0tqRvgGaZhx2tRmXM/SmDzrZMFYAylAcjvkaKFxe8r3Dwntmsgh0LLo3ahQvYnlBrgls7ODdjQ42ZHS8FA2PdaqpM0YGMfJJtyqjE2DfH56t6y/uXoX64pak7oG6aYlOObyiM3TmwSd0NMyH7Kzxuz+x8r8tgI2414qp1EpK+IbrsETq59QQcfAI5Syikpjr4a0rzWrf82V3FD9ZkFrvgO/+pPhxZ58CHZbDIHRlEMQKYRrTsbQJrTT/3wVm2CrO4zASSu3iWmjwCkrA7GUqVFMd20yoNxhbj+/gODuiq/c+u7CbcOF9m0BXb1CboPX34hrQ3/WeccKD08peKA1l2DmW8llH6U8UbQKaLs0p3ANuqs4HY33M/8eAzst4S9wITlpX8pR54nfC3hyPSvR3KliSFCy0eQzUWLbSW3DU0K5N3f9MrGOLOs9vopVBa/iKZGe3p1YQkL79Ax/fbbgTzn9McrtM=
  app: kakumemo
  on:
    repo: full-party/CrossUp
