language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: F6byt2x1Z8R9cUSEUX8j62jjH7WzXul0nJFsaCzzDM8bKQZDvT3dpB7Py59pyfxCqwiIPhosCqjX55Y5d4W+PjGA985hIET1XxjCE0AHQPGUrMJf1W8P45/JwKWvSzfTB/c65nDodOmzc20+2U2ESn5NHWTlP7zhQ9RUvv2QQpVV4Qir2002N9zjWfRUyq8iDBmZ/KhpKJJSGOwpBpDBADu0Ki3RFY2B/u7/nGtBicigmCamcKg6hK2HCNPPktCRrSFgKLkHJkQDVvxVFW89/9chnYLSlapB3q7vc/UdYonWyFFDdqNVcRAp4C2+Vtfb2Od0QUsZjO6saXBZG1nmYuOOPenV2fphougR0SPf/SpYXzRU6TvHVLzS0uUNtlGZt+TsLQ2lVO4CokJTKo2kKdcwX9NAWr3Mvp0pxo6B6c//bMOhUfRH2XUsLDAeB1Xdjy0+U+ShhOmh8gRiUW9Edc/1+dnOcUPLqOAzYp+59MCECTG9wYp6f79RzkAA0V1FYrmL4zLBfkv0J2Am7Tx+wwSlvqPvZnNvPt5qxODwS7pdfcgKTg4IvjGFZkrzkgRgkuY4jEzgZNTJZ3B5cgYQ3BhPPO4vYcAHM4f6TTE6+v+5mTKHCILiH31cPzDO2vZVGkplJpdTDyDfUMpiy8JmnzdFG91IVKllOH3/o7JS1Ys=
  app: kakumemo
  on:
    repo: full-party/CrossUp
  run:
  - php artisan migrate --force
