language: php
php:
 - 7.1
before_script:
 - mysql -uroot -e "create database cross_up"
install: true
script:
 - cp .env.testing .env
 - composer install
 - php artisan migrate --force --seed
 - phpunit
notifications:
 slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
 - mysql
deploy:
 provider: heroku
 api_key:
  secure: db849b51-7ec7-408e-97dd-7f456080940f
  app: kakumemo