language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: vPwo2dv52roAajAgu1MUcQk2RITu0eSE9LLBK1NmFcD8N5mvzSjIfh6lhb1ORcK3w7DB30qTFnB4IROaQeqZqysr2NRz13YfQZRayD7bCncOptBnhzF0pTvBfHXvFNvXvD74wlQEXD3bqZvENq/FuWqNZydhQHUi9jGh4MCx4RFeTegU+jK6VkOdXBSKMdhSNnS8htaTH0vxUjRoSOFN+J65/fkfr3t+i9nYvRbyPjzRhksBmTkpczjjbLZeyU+dPX9Oh2CeMQ5ABVPjpPiNjI3VQoH6UtxpQm0vMyeamIc0M7ku1UobQu0GX+8ObBDtfteFpbTsZ/6JtWcEBTygiZZT8b6sPKyg+qwScBhZn7zvPjJHoi8iTqy17+2PQny1VmpQZ0coXG6UTWWlxHln6oBS9CBSva2vURecHNvC01AZ1X/wXMVcl78cXCXofaxBAkemTL7OH3Kl/EL5yo7Mc0a53TNLAW3ynIzl0eVWk/h3A0AridvZg3nFqJAPRuPOgwwcGcFfGv7p2fCrfdeNJ6IyqONTcuhkMJ768Nta9JPsxkBXB0jRo7vi0Bakjd2oiggEt0xcYvr/bJoUbeEljX31f99m0YuuUmNlTrSDKn3EbHdvHm7A34KzdgFrBICG7knpC0xQUtWEhWNawR00c6h3p1vSl5OJU4eWX0G66yw=
  app: kakumemo
  on:
    repo: full-party/CrossUp
  run:
  - php artisan migrate --force
