language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: k5Ku73e8LWAesCp9QfFdG+b04J1ER75rSaIW7RhByj2d624IoVU54VCqz3OI0nkzYkefI/IyWoU99IE/d2Z76GQ1eGy4fVs34baauGOwUo55yvfrLhkhiQAa8jdxxhrlOMCpHNPenBGdJye+wVUbFzpOrD+vBaRNqoYZGq/8X69orTx/u7crMWxrjxexQZTjZQRiE1umqKsupg3u51Luhby+rh8atkaCdb9z86hCD4aWtmK6GUVas2GUfLgiFRJH36r000vESnaTALLXRKEtV5CtI40OUyl7XYManX/UBosUCEwco2hHwQKuJ4l5Ex/aLOvQOW+bk5BS+W6OoifCUF/4CA9wmFV2v1SfgrvXJ31FKZ8zBshPjAp7BFGtojbzp1Gl8L9bM2oh8D5tinF/0rY8jlaBFy/HWHKgpHSJcJFF6xdgWGxq63fSzUYsd5dHmEXE2xIfsJorrl1ok+KHkT/416RvL+LUZhbfaMDQz1iUdDWc1adiBgzAHbtVDSOGLmNiQTb/7//t4p3iyVXWYNa38NjrwvBnNGXImvCmJAKDlignHIIqzSqTGbVcrIj+qvwSyjRo0MsMwGPdh5PPQual0wb1k38fyQibrUXHhao1d0uOGtZ7aNdUMT3WhQDZDXIzW2I+wjx+U0r+YTYQ76GfJYQj+fJcVVvwDvmUPgI=
  app: kakumemo
  on:
    repo: full-party/CrossUp
