language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: Dbp3KpSFmsGbIafU9DfYxpeT4YByRSg1eSqGvrwr5bd5JLrQeqDv5ju46/EG+Exsb8gKvCD4QtuCUGtc69WQbfzcPftB2t0zmkqkuIDyO/uOuuf+VZbz/wjNf/4aDHSu9I7HpI7yoBB3rpp5+Uouzr9YdotnRhhdyAiQskzWJPznM8QR3p+1EYCZMCBgzo6rdXrA0OVnI5BiSWsJm+KQpqEheCgxqvcUzm0/fWH3zNm5R4u2U2bvw1E6gaYFJNFTtxJH58NjVGwBIouiOPQvchyl5O549uYap1P+hF7xN4qG2IbnE66J3sSJq7OsWHorQsl+SYI+jfbcSNNA1qP04MAp8tSHy6bbkj0yUkUkBJArOr27CDOYkiYjJhQhHma2KDfTp4/CC9s6EIqP43AbM776YmfEDafNm9a/Lx9EBHsBVBaES6MT7Sxsu2rqQMts4NH0BWD6GyGNZ9kyQsJBilet8l4VlbfBDTZdEZW+yLfyc93L/xYYp9bjiwPcWP5NO1XurYwXpo2meHRhZ18cgvOaDpPF+Z2vZiHzZQKYuYfCUerVdmucD5kqzPG18ykoOnymLvfzvNn9oECD0h97potStINcodHOnFQclZj8T6CoDnVyVfojCwEMSIMr0OxHmSM22e14t44BAtj4t/zqNBTntEyo9la6jdipSe2yzAw=
  app: kakumemo
