language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: qTQv2ZI3ZIZAl9CccNjnD4LkPKi/DKcRNk3rx7BDil/WLeO240XuB4q71idGFu5MsKrGgf768oxATVsnZSGTpV6E1EEya2aq66O3phRyH67O4mW8e2YhSQbx0hvI6rcKs8BNO5ojjO2+gkMPfSabq0YsthNitFBGWthRcMLxLXg/7HIAuRkK/WxDTht50LHWYhbhR3ZfMYM3nt8W5qXcAFOwsHbGADLAmsXzK7JrgoBkDUfnXvSKnTkw+d9qSy2P0jA1J1I3oF1QAQiWTcKCpoF0hExff0cvuYWUrw8DaGmE0YLvCT8XoZfiqC3bt/QhsnCEw9YFPJDXyoSbLZoYdlTiM3cuRurRP8sVwiElKlbHY5bCUBFAvNFqVciBBKlWCHLBP9ZQSwBufBso67Qe3KMpoCc2QZz+6QqBQtzX06InBLQMyl7xypuuXz8LeifJf9kH4N7YQsPxQxhZihiGpqwXvfJcAFRSt1HvAo2LiBanr8o7Q6jjWgqyGnjh2Cml333MWELj/Tg67VZC1nHMRcf23/xHE4V2b6upnB5cbrba1tiNLRby8EnuVruVitVBBnJ51NqEKxs01kX5OP7BLhavXog62qCvji2xhzRd74kJrwSNG48XsKS64MeGQcgxtmRFmIJjh6jO9VbZSBD8+XzysFAZl4Z25uhtG2t5gvQ=
  app: kakumemo
  on:
    repo: full-party/CrossUp
  run:
  - php artisan migrate --force
