language: php
php:
- 7.1
before_script:
- mysql -uroot -e "create database cross_up"
install: true
script:
- cp .env.travis .env
- composer install
- php artisan migrate --force
- php artisan db:seed
- php artisan db:seed --class=TestDatabaseSeeder
- phpunit
notifications:
  slack: full-party:ITmQQI6GSQEkcoU6e0NN3X2B
services:
- mysql
deploy:
  provider: heroku
  api_key:
    secure: hV59RMpmeA6/o90opVtcyOWytaKU7evYuEgYo9bOST7kkWb9QscAQy3Xa6mUVeb6/Dw5jm1HKkGZcI8CedU9XUoMbwLfew1pXJGxVtthvx+UemdCS56F7UWRPyMof0CX0GFKZJf4njXkO+Q2Xn15bcW2OMkMWjEx9deRLOWvEWItl8Bg2t6R3jznJcm53anAn7uY1vm1vWvPXA8rOf1s3QXWA4YRk5nwdsouRqrOCHRTGQjIa2Rg2sBw5sqfjxbcF2mk0iQ6bScLGDcekXmVCob6sHj54upB9q1GeApHXgQTDQwrtBP0E8P+qhFpwT1SgxFlh7/s7XM22BxBMunoE5lp2pV61x46JL4ao7NOMsSEJlvuOyslXstRVv5D5pW75h6Brolfn8sxPNx8Ofd2wMPis6rRHT50oCUePfSnwgJwnwFlJeB27ibu1vAyUmazXWI1E4b2a4A5submBCJhqtcHYsjgxwuEP6fIQxrGGVB3rSiLVCU4ENIacVnSMzSK5K4T0XLuyCKzXoWCEnKEAQxVAg2HD1Bu6XpgoEo9Fuz3gtdWYjebkLWVqdvZeB5CA1iCWGRc7qLkw8O2y+pVWFSpQUwxt8rtOLWXe10t/+zbWBAbwwXaFKDRMcZRgGE8bLj6n61ybixiZqfSX9BN+LFURv3vaPeUY0uQcwC+I6w=
  app: kakumemo
  on:
    repo: full-party/CrossUp
  run:
    - "php artisan migrate --force"
